import turtle

turtle.pencolor('green')
turtle.forward(250)
turtle.right(90)
turtle.forward(250)
turtle.right(90)
turtle.forward(250)
turtle.right(90)
turtle.forward(250)
turtle.right(90)

turtle.pencolor('blue')
turtle.penup()
turtle.forward(50)
turtle.right(90)
turtle.forward(50)
turtle.pendown()
turtle.right(30)
turtle.forward(50)
turtle.right(60)
turtle.back(50)
turtle.right(60)
turtle.forward(50)
turtle.right(120)
turtle.penup()
turtle.forward(150)
turtle.pendown()
turtle.right(60)
turtle.forward(50)
turtle.right(120)
turtle.forward(50)
turtle.right(120)
turtle.forward(50)
turtle.right(150)
turtle.penup()

turtle.pencolor('red')
turtle.forward(100)
turtle.pendown()
turtle.forward(50)
turtle.right(90)
turtle.forward(150)
turtle.right(90)
turtle.forward(50)
turtle.right(90)
turtle.forward(150)
turtle.right(90)



